### ISSUE TITLE
Quartz valley

### ISSUE THREAD

**Issue by Maxx2310** [Andromeda-Galaxy29/Psammos-Mod#1]
For launching to quartz valley, you need cooper and lead even tho you dont have them in first sector

**Comment by Andromeda-Galaxy29** [comment]
Hello. Thanks for letting me know. The mod is still in development and the campaign still doesnt work properly.

Also how did you find my mod?

**Comment by Andromeda-Galaxy29** [comment]
Fixed. It should work now.
