### ISSUE TITLE
Peat heater accepts liquids for no clear reason

### ISSUE THREAD

**Issue by 000x91** [Andromeda-Galaxy29/Psammos-Mod#19]
It looks like a remnant from the template for ozone/ammonia because the other two heaters do use liquid

https://github.com/Andromeda-Galaxy29/Psammos-Mod/blob/ba4392921a71ed2a81002d51c7c289eb4d4ba9fa/src/psammos/content/PsammosBlocks.java#L1523-L1524

**Comment by Andromeda-Galaxy29** [comment]
Yeah, it was leftover from heat exchanger's code
It'll be fixed in v1.3

**Comment by Andromeda-Galaxy29** [comment]
Fixed in the dev branch (v1.3 beta).
