### ISSUE TITLE
tip is rendered below sciur

### ISSUE THREAD

**Issue by Tinport** [Andromeda-Galaxy29/Psammos-Mod#20]
i dont think this is supposed to happen, but a unit can that walk over walls is rendered under a unit that cant go over walls

**Comment by Tinport** [comment]
![image](https://github.com/user-attachments/assets/ec68df95-558f-4f02-818d-6293961024c5)
![image](https://github.com/user-attachments/assets/24f11a60-53cf-4825-9ee2-fd532fe408d4)
this does not look right

**Comment by Andromeda-Galaxy29** [comment]
Resolved in latest commit to the dev branch
![image](https://github.com/user-attachments/assets/e0566e32-be8f-4cef-8b2c-8e3a439b17a9)
