### ISSUE TITLE
Electric distributor does not have a beam sprite.

### ISSUE THREAD

**Issue by Crimsoncheck** [Andromeda-Galaxy29/Psammos-Mod#3]
Electric distributor only shows a **green line** when connected to another electric distributor.
![Screenshot_20240317-220342_Mindustry.jpg](https://github.com/Andromeda-Galaxy29/Psammos-Mod/assets/163398291/6fa55b48-4903-4de9-a1e7-9391030d4db9)
_*Map taken from sector "The Dried River"._

**Comment by Andromeda-Galaxy29** [comment]
Fixed
